{% set name = "python-localvenv-kernel" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-localvenv-kernel-{{ version }}.tar.gz
  sha256: 930ada9382f21f6da7dab6567e0caeb96f4d239f73aca6a00e6b71f0e97423ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - colorama >=0.4.4,<0.5.dev0

test:
  imports:
    - localvenv_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/goerz/python-localvenv-kernel
  summary: Python Jupyter kernel delegating to a local virtual environment
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goerz
