{% set name = "python-localvenv-kernel" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-localvenv-kernel-{{ version }}.tar.gz
  sha256: f890d16710ddfc3d935c288d42cc6f26ac2e2a318887c2dd20f2c5c41b0b247e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - colorama >=0.4.4,<0.5.dev0

test:
  imports:
    - localvenv_kernel
  commands:
    - pip check
  requires:
    - pip
    - setuptools
    - python {{ python_min }}

about:
  home: https://github.com/goerz/python-localvenv-kernel
  summary: Python Jupyter kernel delegating to a local virtual environment
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goerz
